In [9]:
import pickle

import numpy
import pandas as pd
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder

import tools

In [10]:
path_dataset = tools.data_file('dataset.pkl')
fvs = [y for x in pickle.load(open(path_dataset, 'rb')) for y in x]

df = pd.DataFrame(fvs)
df

tag              str  i_seg  str_len_left  seg_len  left_lo_seg_cnt  \
0      Lstr  Gretchen Wilson      0             0       15                0   
1        Po                .      1            15        1                0   
2        Po                .      2            16        1                0   
3        Po                .      3            17        1                0   
4        Zs                       4            18        1                0   
...     ...              ...    ...           ...      ...              ...   
22526    Pd                -      5            16        1                2   
22527    Nd          1234567      6            17        7                2   
22528    Zs                       7            24        1                2   
22529    Sm                ＋      8            25        1                2   
22530    Zs                       9            26        1                2   

       title_len  right_seg_cnt  right_seg_length  right_lo_seg_cnt  \
0             65             10                65                 0   
1             65              9                50                 0   
2             65              8                49                 0   
3             65              7                48                 0   
4             65              6                47                 0   
...          ...            ...               ...               ...   
22526         27              5                11                 0   
22527         27              4                10                 0   
22528         27              3                 3                 0   
22529         27              2                 2                 0   
22530         27              1                 1                 0   

       i_slot_between_dash  in_quote quote_type label  
0                        0     False                a  
1                        0     False                x  
2                        0     False                x  
3                        0     False                x  
4                        0     False                x  
...                    ...       ...        ...   ...  
22526                   -1     False                x  
22527                    1     False                t  
22528                    1     False                x  
22529                    1     False                x  
22530                    1     False                x  

[22531 rows x 14 columns]

# Column: label

In [11]:
df.label.unique()

array(['a', 'x', 't'], dtype=object)

In [12]:
e13 = LabelEncoder()
df['label'] = e13.fit_transform(df.label.values)

In [13]:
df.label.unique()

array([0, 2, 1], dtype=int64)

# Column: quote_type

In [14]:
df.quote_type.unique()

array(['', '()', '[]', "''", '""', '【】', '“”', '《》', '（）'], dtype=object)

In [15]:
e12 = LabelEncoder()
df['quote_type'] = e12.fit_transform(df.quote_type.values)
df.quote_type.unique()

array([0, 3, 4, 2, 1, 7, 5, 6, 8], dtype=int64)

# Column: in_quote

In [16]:
df.in_quote.unique()

array([False,  True])

In [17]:
df['in_quote'] = df['in_quote'].astype(int)

In [18]:
df['in_quote'].dtype

dtype('int32')

# i_slot_between_dash

In [19]:
df.i_slot_between_dash.unique()

array([ 0, -1,  1,  2,  3,  4,  5,  6], dtype=int64)

# right_lo_seg_cnt

In [20]:
df.right_lo_seg_cnt.unique()

array([ 0,  2,  1,  5,  4,  3,  8,  7,  6,  9, 10, 15, 14, 13, 12, 11],
      dtype=int64)

# right_seg_length

In [21]:
df.right_seg_length.unique()

array([65, 50, 49, 48, 47, 46, 24, 23, 22, 21, 39,  1, 27, 12, 11, 28, 13,
        2, 45, 38, 33, 32, 20, 19, 14,  8,  7, 31, 30, 15,  9, 57, 36, 35,
       54, 44, 43, 26, 25,  6,  5,  4,  3, 18, 17, 34, 16, 56, 51, 10, 37,
       58, 42, 29, 82, 73, 72, 61, 60, 41, 40, 52, 59, 53, 62, 66, 74, 78,
       86, 69, 68, 67, 81, 55, 83, 70, 63, 64, 75, 77, 98, 80, 71, 88, 76,
       84, 79, 90, 93, 89, 87, 85, 95, 92, 97, 91], dtype=int64)

In [22]:
df.isnull().values.any()

False

# right_seg_cnt

In [23]:
df.isnull().values.any()

False

In [24]:
df.right_seg_cnt.unique()

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1, 11, 12, 13, 20, 19, 18, 17,
       16, 15, 14,  0, 26, 25, 24, 23, 22, 21, 33, 32, 31, 30, 29, 28, 27,
       34, 35], dtype=int64)

# title_len

In [25]:
df.isnull().values.any()

False

In [26]:
df.title_len.unique()

array([65, 39, 27, 28, 45, 14, 31, 57, 54, 34, 56, 51, 44, 46, 17, 58, 43,
       30, 29, 19, 36, 82, 26, 47, 20, 32, 49, 33, 52, 40, 35, 59, 38, 42,
       22, 24, 48, 16, 37, 41, 25, 61, 72, 18, 23, 73, 50, 66, 62, 21, 74,
       78, 60, 86, 15, 81, 55, 53, 83, 70, 63, 12, 11, 64, 69, 67, 75, 77,
       98, 71, 88, 84, 13, 68, 76, 90, 79, 93, 10, 85, 95, 89,  8, 97, 87,
       91,  6,  7,  9, 92], dtype=int64)

# left_lo_seg_cnt

In [27]:
df.isnull().values.any()

False

In [28]:
df.left_lo_seg_cnt.unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int64)

# seg_len

In [29]:
df.isnull().values.any()

False

In [30]:
df.seg_len.unique()

array([15,  1, 22, 21, 10,  6,  5, 12, 19,  7,  8,  9, 11, 20, 17,  2, 16,
        4, 26, 13, 18, 30, 24, 23, 14,  3, 29, 28, 34, 35, 27, 25, 53, 31,
       32, 37, 36, 40, 38, 33, 39, 64, 43, 42], dtype=int64)

# str_len_left

In [31]:
df.isnull().values.any()

False

In [32]:
df.str_len_left.unique()

array([ 0, 15, 16, 17, 18, 19, 41, 42, 43, 44, 38, 26, 27,  6,  7, 12, 13,
       25,  1,  8,  9, 22, 23, 10, 21, 45, 46, 56, 11, 28, 29, 30, 47, 48,
       49, 50, 51, 52, 24, 40, 55, 34, 35, 36, 20, 37,  4,  5, 14, 53, 54,
       71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 31, 32, 33, 57, 39,  2,
        3, 60, 58, 59, 66, 67, 64, 65, 61, 68, 69, 85, 82, 62, 63, 89, 90,
       92, 93, 94, 95, 96, 84, 86, 83, 70, 87, 88, 91], dtype=int64)

# i_seg

In [33]:
df.isnull().values.any()

False

In [34]:
df.i_seg.unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34], dtype=int64)

# str

In [35]:
df['str']

0        Gretchen Wilson
1                      .
2                      .
3                      .
4                       
              ...       
22526                  -
22527            1234567
22528                   
22529                  ＋
22530                   
Name: str, Length: 22531, dtype: object

In [36]:
e1 = LabelEncoder()
df['str'] = e1.fit_transform(df.str.values)
df['str']

0        1399
1          15
2          15
3          15
4           0
         ... 
22526      14
22527      39
22528       0
22529    5095
22530       0
Name: str, Length: 22531, dtype: int32

# tag

In [37]:
df['tag']

0        Lstr
1          Po
2          Po
3          Po
4          Zs
         ... 
22526      Pd
22527      Nd
22528      Zs
22529      Sm
22530      Zs
Name: tag, Length: 22531, dtype: object

In [38]:
e0 = LabelEncoder()
df['tag'] = e0.fit_transform(df.tag.values)
df['tag']

0         4
1        13
2        13
3        13
4        18
         ..
22526     9
22527     7
22528    18
22529    16
22530    18
Name: tag, Length: 22531, dtype: int32

In [39]:
df

tag   str  i_seg  str_len_left  seg_len  left_lo_seg_cnt  title_len  \
0        4  1399      0             0       15                0         65   
1       13    15      1            15        1                0         65   
2       13    15      2            16        1                0         65   
3       13    15      3            17        1                0         65   
4       18     0      4            18        1                0         65   
...    ...   ...    ...           ...      ...              ...        ...   
22526    9    14      5            16        1                2         27   
22527    7    39      6            17        7                2         27   
22528   18     0      7            24        1                2         27   
22529   16  5095      8            25        1                2         27   
22530   18     0      9            26        1                2         27   

       right_seg_cnt  right_seg_length  right_lo_seg_cnt  i_slot_between_dash  \
0                 10                65                 0                    0   
1                  9                50                 0                    0   
2                  8                49                 0                    0   
3                  7                48                 0                    0   
4                  6                47                 0                    0   
...              ...               ...               ...                  ...   
22526              5                11                 0                   -1   
22527              4                10                 0                    1   
22528              3                 3                 0                    1   
22529              2                 2                 0                    1   
22530              1                 1                 0                    1   

       in_quote  quote_type  label  
0             0           0      0  
1             0           0      2  
2             0           0      2  
3             0           0      2  
4             0           0      2  
...         ...         ...    ...  
22526         0           0      2  
22527         0           0      1  
22528         0           0      2  
22529         0           0      2  
22530         0           0      2  

[22531 rows x 14 columns]

In [40]:
(df.shape[1], )

(14,)